name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
    - name: List files in the repository
      run: |
          ls ${{ github.workspace }}
    - run: echo "🍏 This job's status is ${{ job.status }}."